version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "dev"]
      interval: 1s
      retries: 30
      timeout: 1s

volumes:
  postgres-data: null
